### ISSUE TITLE
Write quarto template for slides with Monash branding

### ISSUE THREAD

**Issue by robjhyndman** [numbats/numbathackathon#24]
@emitanaka may have some suitable css already developed.

**Comment by emitanaka** [comment]
Quarto template here: https://github.com/numbats/monash/tree/master/inst/rmarkdown/templates/revealjs

**Comment by cynthiahqy** [comment]
Mostly done here -- https://github.com/JayaniLakshika/quarto_presentation_template
- [ ] missing background images
- [ ] template name?
- [ ] Has a visual mode bug where Studio Visual Canonical mode is injecting escapes into html (need some sort of "as-is") fix.

**Comment by cynthiahqy** [comment]
The injection also makes the iframe code open 5000 tabs upon rendering

**Comment by robjhyndman** [comment]
Repo: https://github.com/numbats/monash-quarto-presentation

**Comment by cynthiahqy** [comment]
Modifying title slide -- beyond `$presentation-title-slide-text-align` which only affects the title, but not the author (which was still centre aligned)

Adding this into `monash.scss` helped: 
https://github.com/mcanouil/quarto-revealjs-coeos/blob/7cc21feed329acbe6e19a11f9f57eb37d2977ceb/_extensions/coeos/coeos.scss#L33-L58

**Comment by cynthiahqy** [comment]
You can replace the HTML template using template partials: https://quarto.org/docs/journals/templates.html#revealjs-partials

**Comment by cynthiahqy** [comment]
- https://quarto.org/docs/reference/dates.html#using-a-date-style

**Comment by cynthiahqy** [comment]
Need to fix responsive aspect ratio if using Monash backgrounds -- 
What does `height:` and `width:` YAML do?

```yaml
    revealjs:
      logo: images/monash-one-line-black-rgb.png
      theme: assets/monash.scss
      width: 1280
      height: 720
      css: [assets/tachyons-addon.css, assets/custom.css]
      include-after-body: "assets/after-body.html"
      include-in-header: "assets/header.html"
```

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/29718979/220918552-16222b93-b89c-4266-a710-94a209c0f863.png">
